### ISSUE TITLE
Panic in v0.30.0-rc3

### ISSUE THREAD

**Issue by aa-matthias** [prometheus-community/windows_exporter#1818]
### Current Behavior

Crash on Startup

### Expected Behavior

Should work just fine

### Steps To Reproduce

```Markdown
Install collector and try scraping metrics
```

### Environment

- windows_exporter Version: v0.30.0-rc3
- Windows Server Version: 2019

### windows_exporter logs

```shell
panic: reflect: Field index out of range

goroutine 23 [running]:
reflect.Value.Field({0x12eaf80?, 0xc00039e410?, 0xc000392180?}, 0x11e9c00?)
        C:/hostedtoolcache/windows/go/1.23.4/x64/src/reflect/value.go:1273 +0x92
github.com/prometheus-community/windows_exporter/internal/pdh.(*Collector).collectRoutine.func1(0xc0000897a0, {0x11e9c40, 0xc00022e1c0}, 0xc0000aeaa8, 0xc000267f68, 0xc0000aeaa4, 0xc000267f50)
        D:/a/windows_exporter/windows_exporter/internal/pdh/collector.go:395 +0xf9f
github.com/prometheus-community/windows_exporter/internal/pdh.(*Collector).collectRoutine(0xc0000897a0)
        D:/a/windows_exporter/windows_exporter/internal/pdh/collector.go:408 +0xd4
created by github.com/prometheus-community/windows_exporter/internal/pdh.NewCollectorWithReflection in goroutine 16
        D:/a/windows_exporter/windows_exporter/internal/pdh/collector.go:212 +0xd7b
```

**Comment by jkroepke** [comment]
What the list of enabled collectors?
