### ISSUE TITLE
windows_exporter crash : unexpected return pc

### ISSUE THREAD

**Issue by woodytec** [prometheus-community/windows_exporter#696]
Hello,

I'm running windows_exporter (v0.15.0) under Windows Server 2019 to get my system metrics into Prometheus. The process starts and runs but becomes unreachable after some time.

Here is the output I get from windows_exporter : 
```
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime: unexpected return pc for github.com/prometheus/client_golang/prometheus.(*Desc).String called from 0x123bd020
stack: frame={sp:0x123bcebc, fp:0x123bcf38} stack=[0x123bc000,0x123bd000)
123bce3c:  00000000  00000000  00000000  00000000 
123bce4c:  00000000  00000000  00000000  00000000 
123bce5c:  00000000  00000000  00000000  00000000 
123bce6c:  00000000  00000000  00000000  00000000 
123bce7c:  00000000  777d074c  00000000  00000000 
123bce8c:  00000000  00000246  00000000  0050d000 
123bce9c:  00000000  3353fda0  00000000  3353ec70 
123bceac:  00000000  77753600  00000000  010e508d <github.com/prometheus/client_golang/prometheus.(*Desc).String+29> 
123bcebc: <00000000  0020027f  00000000  00e020e5 <runtime.uint32tofloat64+21> 
123bcecc:  00000000  00000000  00000000  00001fa0 
123bcedc:  0000ffff  7788432c  00000000  0000ffff 
123bceec:  00000000  00000000  00000000  00000000 
123bcefc:  00000000  00000000  00000000  00000000 
123bcf0c:  00000000  123bcf74  00000000  7788432c 
123bcf1c:  777ca6f1  00000000  123bcf74  777cb125 
123bcf2c:  77881774  123bd070 !123bd020 >00000001 
123bcf3c:  00000000  123bd020  123bd070  00000003 
123bcf4c:  007b80c0  123bd020  123bd070  00004011 
123bcf5c:  007b80b8  00000000  004d6000  ffffffff 
123bcf6c:  00697463  20676e69  123bd008  777c726f 
123bcf7c:  00000001  00000258  00000009  777c7282 
123bcf8c:  00000000  123bd070  00000000  00000000 
123bcf9c:  00000000  00000000  00000000  00000000 
123bcfac:  00000000  00000000  00000000 
github.com/prometheus/client_golang/prometheus.(*Desc).String(0x1, 0x0, 0x123bd020)
	c:/gopath/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/desc.go:170 +0x1d
created by net/http.(*connReader).startBackgroundRead
	C:/go/src/net/http/server.go:686 +0xb0

goroutine 1 [chan receive, 1 minutes]:
main.main()
	C:/gopath/src/github.com/prometheus-community/windows_exporter/exporter.go:421 +0x12ac

goroutine 36 [chan receive, locked to thread]:
github.com/StackExchange/wmi.(*SWbemServices).process(0x121bc640, 0x12478280)
	c:/gopath/pkg/mod/github.com/!stack!exchange/wmi@v0.0.0-20180725035823-b12b22c5341f/swbemservices.go:115 +0x3a0
created by github.com/StackExchange/wmi.InitializeSWbemServices
	c:/gopath/pkg/mod/github.com/!stack!exchange/wmi@v0.0.0-20180725035823-b12b22c5341f/swbemservices.go:41 +0xb2

goroutine 10 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	C:/go/src/runtime/proc.go:312
sync.runtime_notifyListWait(0x121bd108, 0xb)
	C:/go/src/runtime/sema.go:513 +0x123
sync.(*Cond).Wait(0x121bd100)
	C:/go/src/sync/cond.go:56 +0x66
net/http.(*connReader).abortPendingRead(0x121bd0e0)
	C:/go/src/net/http/server.go:738 +0x8a
net/http.(*response).finishRequest(0x12218000)
	C:/go/src/net/http/server.go:1625 +0x89
net/http.(*conn).serve(0x1214e000, 0x13b5b40, 0x121bd0c0)
	C:/go/src/net/http/server.go:1930 +0x7f1
created by net/http.(*Server).Serve
	C:/go/src/net/http/server.go:2969 +0x2b9

goroutine 9 [syscall, 1 minutes, locked to thread]:
syscall.Syscall(0x75063b40, 0x2, 0x4d0, 0xffffffff, 0x0, 0x0, 0x0, 0x0)
	C:/go/src/runtime/syscall_windows.go:188 +0xbb
golang.org/x/sys/windows.WaitForSingleObject(0x4d0, 0xffffffff, 0x0, 0x0, 0x0)
	c:/gopath/pkg/mod/golang.org/x/sys@v0.0.0-20190507160741-ecd444e8653b/windows/zsyscall_windows.go:1110 +0x6e
golang.org/x/sys/windows/svc.(*event).Wait(0x121f8014, 0x0, 0x0)
	c:/gopath/pkg/mod/golang.org/x/sys@v0.0.0-20190507160741-ecd444e8653b/windows/svc/event.go:38 +0x2f
golang.org/x/sys/windows/svc.(*service).run(0x1214a000)
	c:/gopath/pkg/mod/golang.org/x/sys@v0.0.0-20190507160741-ecd444e8653b/windows/svc/service.go:225 +0x35
created by golang.org/x/sys/windows/svc.Run
	c:/gopath/pkg/mod/golang.org/x/sys@v0.0.0-20190507160741-ecd444e8653b/windows/svc/service.go:350 +0x174

goroutine 38 [IO wait]:
internal/poll.runtime_pollWait(0x249c18, 0x72, 0x13b18f0)
	C:/go/src/runtime/netpoll.go:220 +0x4b
internal/poll.(*pollDesc).wait(0x1205ed54, 0x72, 0x161a200, 0x0, 0x0)
	C:/go/src/internal/poll/fd_poll_runtime.go:87 +0x37
internal/poll.execIO(0x1205ec74, 0x1209ddb8, 0x0, 0x0, 0x0)
	C:/go/src/internal/poll/fd_windows.go:175 +0xce
internal/poll.(*FD).acceptOne(0x1205ec60, 0x60c, 0x123341e0, 0x2, 0x2, 0x1205ec74, 0x634, 0x98000004, 0x1209de9c, 0xdcc452)
	C:/go/src/internal/poll/fd_windows.go:810 +0x7d
internal/poll.(*FD).Accept(0x1205ec60, 0x1209dea4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/go/src/internal/poll/fd_windows.go:844 +0x126
net.(*netFD).accept(0x1205ec60, 0x1a, 0x165d080, 0x12086088)
	C:/go/src/net/fd_windows.go:139 +0x66
net.(*TCPListener).accept(0x121c4f40, 0x121aa160, 0xfc1f9200, 0xddcfcd)
	C:/go/src/net/tcpsock_posix.go:139 +0x27
net.(*TCPListener).Accept(0x121c4f40, 0x1209df0c, 0xc, 0x12084b60, 0xfec679)
	C:/go/src/net/tcpsock.go:261 +0x57
net/http.(*Server).Serve(0x121917a0, 0x13b4ff0, 0x121c4f40, 0x0, 0x0)
	C:/go/src/net/http/server.go:2937 +0x1eb
net/http.(*Server).ListenAndServe(0x121917a0, 0x121917a0, 0x2)
	C:/go/src/net/http/server.go:2866 +0x9c
net/http.ListenAndServe(...)
	C:/go/src/net/http/server.go:3120
main.main.func5(0x12006ab0)
	C:/gopath/src/github.com/prometheus-community/windows_exporter/exporter.go:417 +0xe0
created by main.main
	C:/gopath/src/github.com/prometheus-community/windows_exporter/exporter.go:415 +0x1291

goroutine 240 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x249a5c, 0x72, 0x13b18f0)
	C:/go/src/runtime/netpoll.go:220 +0x4b
internal/poll.(*pollDesc).wait(0x121a8514, 0x72, 0x161a200, 0x0, 0x0)
	C:/go/src/internal/poll/fd_poll_runtime.go:87 +0x37
internal/poll.execIO(0x121a8434, 0x132d6dc, 0x1ae3101, 0x9d, 0x0)
	C:/go/src/internal/poll/fd_windows.go:175 +0xce
internal/poll.(*FD).Read(0x121a8420, 0x12288000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/go/src/internal/poll/fd_windows.go:441 +0x100
net.(*netFD).Read(0x121a8420, 0x12288000, 0x1000, 0x1000, 0x1, 0x121313a0, 0xe0b2bb)
	C:/go/src/net/fd_posix.go:55 +0x3f
net.(*conn).Read(0x121cea48, 0x12288000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/go/src/net/net.go:182 +0x67
net/http.(*connReader).Read(0x12131340, 0x12288000, 0x1000, 0x1000, 0x48, 0x8, 0x61)
	C:/go/src/net/http/server.go:798 +0x132
bufio.(*Reader).fill(0x12086ba0)
	C:/go/src/bufio/bufio.go:101 +0xeb
bufio.(*Reader).ReadSlice(0x12086ba0, 0xffffff0a, 0x3fffff, 0xdab69f, 0x123e8500, 0x80, 0x80)
	C:/go/src/bufio/bufio.go:360 +0x32
bufio.(*Reader).ReadLine(0x12086ba0, 0x123e8500, 0x120306c0, 0xe0b60e, 0x165cd20, 0x0, 0xdabd5c)
	C:/go/src/bufio/bufio.go:389 +0x2a
net/textproto.(*Reader).readLineSlice(0x12131380, 0x123e8500, 0xdb48b3, 0x0, 0x0, 0x0)
	C:/go/src/net/textproto/reader.go:58 +0x53
net/textproto.(*Reader).ReadLine(...)
	C:/go/src/net/textproto/reader.go:39
net/http.readRequest(0x12086ba0, 0x0, 0x123e8500, 0x0, 0x0)
	C:/go/src/net/http/request.go:1012 +0x89
net/http.(*conn).readRequest(0x1204d7a0, 0x13b5b40, 0x12131320, 0x0, 0x0, 0x0)
	C:/go/src/net/http/server.go:984 +0x1ca
net/http.(*conn).serve(0x1204d7a0, 0x13b5b40, 0x12131320)
	C:/go/src/net/http/server.go:1851 +0x622
created by net/http.(*Server).Serve
	C:/go/src/net/http/server.go:2969 +0x2b9

goroutine 239 [IO wait]:
internal/poll.runtime_pollWait(0x249af0, 0x72, 0x13b18f0)
	C:/go/src/runtime/netpoll.go:220 +0x4b
internal/poll.(*pollDesc).wait(0x121a83b4, 0x72, 0x161a200, 0x0, 0x0)
	C:/go/src/internal/poll/fd_poll_runtime.go:87 +0x37
internal/poll.execIO(0x121a82d4, 0x132d6dc, 0xdf8e01, 0x0, 0x2)
	C:/go/src/internal/poll/fd_windows.go:175 +0xce
internal/poll.(*FD).Read(0x121a82c0, 0x121d0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/go/src/internal/poll/fd_windows.go:441 +0x100
net.(*netFD).Read(0x121a82c0, 0x121d0000, 0x1000, 0x1000, 0x1, 0x1, 0xe0b2bb)
	C:/go/src/net/fd_posix.go:55 +0x3f
net.(*conn).Read(0x121cea38, 0x121d0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/go/src/net/net.go:182 +0x67
net/http.(*connReader).Read(0x12131280, 0x121d0000, 0x1000, 0x1000, 0x49, 0x8, 0xffffffff)
	C:/go/src/net/http/server.go:798 +0x132
bufio.(*Reader).fill(0x12086b10)
	C:/go/src/bufio/bufio.go:101 +0xeb
bufio.(*Reader).ReadSlice(0x12086b10, 0x1d0a0a, 0x12, 0xdab782, 0x0, 0x0, 0x0)
	C:/go/src/bufio/bufio.go:360 +0x32
bufio.(*Reader).ReadLine(0x12086b10, 0x124be000, 0x120306c0, 0xe0b60e, 0x165cd20, 0x0, 0x12d8420)
	C:/go/src/bufio/bufio.go:389 +0x2a
net/textproto.(*Reader).readLineSlice(0x120c13a0, 0x124be000, 0x0, 0x0, 0x0, 0x0)
	C:/go/src/net/textproto/reader.go:58 +0x53
net/textproto.(*Reader).ReadLine(...)
	C:/go/src/net/textproto/reader.go:39
net/http.readRequest(0x12086b10, 0x0, 0x124be000, 0x0, 0x0)
	C:/go/src/net/http/request.go:1012 +0x89
net/http.(*conn).readRequest(0x1204d680, 0x13b5b40, 0x12131260, 0x0, 0x0, 0x0)
	C:/go/src/net/http/server.go:984 +0x1ca
net/http.(*conn).serve(0x1204d680, 0x13b5b40, 0x12131260)
	C:/go/src/net/http/server.go:1851 +0x622
created by net/http.(*Server).Serve
	C:/go/src/net/http/server.go:2969 +0x2b9

goroutine 401 [IO wait]:
internal/poll.runtime_pollWait(0x2499c8, 0x72, 0x13b18f0)
	C:/go/src/runtime/netpoll.go:220 +0x4b
internal/poll.(*pollDesc).wait(0x1205e934, 0x72, 0x161a200, 0x0, 0x0)
	C:/go/src/internal/poll/fd_poll_runtime.go:87 +0x37
internal/poll.execIO(0x1205e854, 0x132d6dc, 0x801, 0x0, 0xfe7b3d)
	C:/go/src/internal/poll/fd_windows.go:175 +0xce
internal/poll.(*FD).Read(0x1205e840, 0x124d8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/go/src/internal/poll/fd_windows.go:441 +0x100
net.(*netFD).Read(0x1205e840, 0x124d8000, 0x1000, 0x1000, 0x1, 0xdab101, 0xe0b2bb)
	C:/go/src/net/fd_posix.go:55 +0x3f
net.(*conn).Read(0x1209ee58, 0x124d8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/go/src/net/net.go:182 +0x67
net/http.(*connReader).Read(0x120c12c0, 0x124d8000, 0x1000, 0x1000, 0x48, 0x8, 0x1)
	C:/go/src/net/http/server.go:798 +0x132
bufio.(*Reader).fill(0x12404780)
	C:/go/src/bufio/bufio.go:101 +0xeb
bufio.(*Reader).ReadSlice(0x12404780, 0xffffff0a, 0x1ff, 0xdab69f, 0x1206eb80, 0x80, 0x80)
	C:/go/src/bufio/bufio.go:360 +0x32
bufio.(*Reader).ReadLine(0x12404780, 0x1206eb80, 0x1219e480, 0xe0b60e, 0x165cd20, 0x0, 0x12d8420)
	C:/go/src/bufio/bufio.go:389 +0x2a
net/textproto.(*Reader).readLineSlice(0x12183c00, 0x1206eb80, 0x0, 0x0, 0x0, 0x0)
	C:/go/src/net/textproto/reader.go:58 +0x53
net/textproto.(*Reader).ReadLine(...)
	C:/go/src/net/textproto/reader.go:39
net/http.readRequest(0x12404780, 0x0, 0x1206eb80, 0x0, 0x0)
	C:/go/src/net/http/request.go:1012 +0x89
net/http.(*conn).readRequest(0x1214e360, 0x13b5b40, 0x120c12a0, 0x0, 0x0, 0x0)
	C:/go/src/net/http/server.go:984 +0x1ca
net/http.(*conn).serve(0x1214e360, 0x13b5b40, 0x120c12a0)
	C:/go/src/net/http/server.go:1851 +0x622
created by net/http.(*Server).Serve
	C:/go/src/net/http/server.go:2969 +0x2b9
eax     0x0
ebx     0xdd62cb
ecx     0x12031230
edx     0x0
edi     0x88301
esi     0x2
ebp     0x1
esp     0x123bceb8
eip     0x0
eflags  0x10206
cs      0x23
fs      0x53
gs      0x2b
```

I have no idea how to solve this. I first thought it was a network problem (such as too many TCP connections opened) as Prometheus indicates ``` dial tcp 127.0.0.1:30633: connectex: No connection could be made because the target machine actively refused it```, but looking at TCP details on port 30633 showed a total of 0 opened TCP connections.

I'm spawning windows_exporter that way : ```.\windows_exporter.exe --config.file="C:\Program Files\windows_exporter\config\windows_exporter.yaml"```.

Is there a way to fix that ?

**Comment by breed808** [comment]
This is interesting. Some questions:

1. Are multiple `windows_exporter` instances running on the same host?
2. How long does the exporter run before crashing?
3. Is the issue reproducible or intermittent?
4. Does the issue occur on other hosts, or just the one?
5. Are you able to provide the exporter configuration file?
6. What `scrape_interval` is set in Prometheus for this host?

The Prometheus client libraries were updated in #669, it may be worth building the exporter from `master` and testing if the issue is present there.

**Comment by woodytec** [comment]
Hi, here are some details : 

1.  No, only one node exporter is running on each host.
2. It really depends. It has sometimes been running for a couple of hours, but most of the time it crashes after 4 or 5 minutes.
3. It seems to depend on the host. I had the issue on 3 different virtual machines, but could not reproduce it on others...
4. The exact same issue happens on three VMs, with the same OS and almost the same configuration (but different hostnames and IPs)
5. Sure, here it is
```
telemetry:
    addr: "127.0.0.1:30633"
    path: "/metrics"

collectors:
  enabled: cpu,cs,dhcp,dns,exchange,logical_disk,memory,net,os,process,service,system,tcp,time,thermalzone

collector:
  process:
    whitelist: "myservice.+|MyService.+|MYSERVICE.+"
  service:
    services-where: "Name='MyService'"
```
6. I'm using a 10 seconds scrape interval.

I'll build the exporter as you mentionned to see if the issue is still present.

**Comment by woodytec** [comment]
I've rebuilt the exporter as you mentionned. The issue seems to be fixed !

The exporter has been running for a bit more than 2 days without any crash. On other VMs without the rebuild it crashed after a couple of minutes.

**Comment by breed808** [comment]
That's good to hear, sounds like the older client libraries were responsible for the issue.
The fix will be available in the next release though you should be fine to build from master and run from that in the meantime. If there's any issues just let us know.
